system:
    default:
        css:
            files:
                - '@EzSystemsRESTDemoBlockBundle/Resources/public/css/block.css'
                - '@EzSystemsRESTDemoBlockBundle/Resources/public/css/photos-selector.css'
