services:
    ez_systems.landing_page.block.rest:
        class: EzSystems\RESTDemoBlockBundle\Block\RESTDemoBlock
        tags:
            - { name: landing_page_field_type.block_type, alias: restdemo }
