services:
    ez_systems.landing_page.block.rest:
        class: EzSystems\RESTDemoBlockBundle\Block\RESTDemoBlock
        arguments:
            - @ez_systems.landing_page.rest.block.jsonplaceholder
        tags:
            - { name: landing_page_field_type.block_type, alias: restdemo }

    ez_systems.landing_page.rest.block.jsonplaceholder:
        class: EzSystems\RESTDemoBlockBundle\REST\JSONPlaceholder
        arguments:
            - %restblock.api_endpoint%
            - @guzzle.client

    guzzle.client:
        class: GuzzleHttp\Client
